version: '3.8'

services:
  mail-temp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail-temp
    restart: always
    environment:
      # 域名配置
      - MAIL_DOMAIN=example.com
      
      # Web服务配置
      - WEB_PORT=8080
      - DEBUG_MODE=true
      
      # SMTP服务配置（使用非特权端口，避免权限问题）
      - SMTP_PORT=2525
      
      # Redis存储配置（单一环境变量）redis://[:password@]host[:port][/db-number]
      - REDIS_URL=redis://:password@example.com:6379/7
      
      # Ollama API配置 - 按优先级排序尝试不同的连接方式
      - OLLAMA_API_URL=http://example.com:11434/api/generate  # Docker默认网桥IP
    ports:
      - "25:2525"   # SMTP服务端口 - 主机的25端口映射到容器的2525端口
      - "7015:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 添加宿主机映射
    network_mode: "bridge"  # 明确指定网络模式
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    driver: bridge 